server:
  port: 8000

spring:
  application:
    name: traffic-counter-api

  datasource:
    url: jdbc:postgresql://localhost:5432/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      idle-timeout: 30000
      max-lifetime: 600000
      connection-timeout: 30000

    jpa:
      database-platform: org.hibernate.dialect.PostgreSQLDialect
      hibernate:
        ddl-auto: validate
      show-sql: false
      properties:
        hibernate:
          format_sql: true
          jdbc:
            batch_size: 1000
            time_zone: UTC
          order_inserts: true
          order_updates: true

    flyway:
      enabled: true
      clean-disabled: false   # true em PROD
      locations: classpath:db/migration